---
services:
  portfwd-client:
    # Tested with docker.io/dmotte/portfwd-client:v2026.08.27.1529
    image: docker.io/dmotte/portfwd-client:latest
    restart: always
    volumes:
      - ./volumes/portfwd-client/known_hosts:/opt/sshset/data/known-hosts/known_hosts:ro
      - ./volumes/portfwd-client/id_ed25519:/opt/sshset/data/identity-keys/id_ed25519:ro
    environment: { USERNGO_NAME: myuser }
    command: myuser@myserver.example.com -R8001:traefik:80

  traefik:
    # Tested with docker.io/library/traefik:v3.7.12
    # Note: when upgrading between different Traefik minor versions, see
    # https://doc.traefik.io/traefik/migrate/v3/
    image: docker.io/library/traefik:v3.7
    restart: always
    volumes:
      - ./volumes/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./volumes/traefik/dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro

  webauthn-proxy:
    image: docker.io/dmotte/webauthn-proxy:latest
    build: build
    restart: always
    volumes:
      - ./volumes/webauthn-proxy-config/config.yml:/opt/config/config.yml:ro
      - ./volumes/webauthn-proxy-config/cooks.yml:/opt/config/cred-parts/cooks.yml:ro
      - ./volumes/webauthn-proxy-config/users.yml:/opt/config/cred-parts/users.yml:ro

  webauthn-admin: # Inspired by https://github.com/dmotte/misc/tree/main/examples/docker-compose/sftpgo
    image: docker.io/drakkan/sftpgo:v2.7-alpine
    restart: always
    ports: ["2022:2022"]
    volumes:
      - webauthn-admin-home:/var/lib/sftpgo
      - ./volumes/webauthn-proxy-config/users.yml:/serve/users.yml
    command: >
      sftpgo portable --log-file-path=/dev/stdout --log-level=info
      --sftpd-port=2022 --username=user --directory=/serve
      --permissions=list,download,upload,overwrite

  whoami:
    image: docker.io/traefik/whoami:v1.10
    restart: always
    hostname: whoami

volumes:
  webauthn-admin-home: {}
