---
services:
  portmap-client:
    image: docker.io/dmotte/portmap-client:latest
    restart: always
    volumes:
      - ./volumes/portmap-client/known_hosts:/known_hosts:ro
      - ./volumes/portmap-client/ssh-client-key.pem:/ssh_client_key:ro
    command: portmap@myserver.example.com -NvR8001:traefik:80

  traefik:
    image: docker.io/library/traefik:v3.0
    restart: always
    volumes:
      - ./volumes/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./volumes/traefik/dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro

  webauthn-proxy:
    image: docker.io/dmotte/webauthn-proxy:latest
    build: build
    restart: always
    volumes:
      - ./volumes/webauthn-proxy-config/config.yml:/opt/config/config.yml:ro
      - ./volumes/webauthn-proxy-config/cooks.yml:/opt/config/cred-parts/cooks.yml:ro
      - ./volumes/webauthn-proxy-config/users.yml:/opt/config/cred-parts/users.yml:ro

  webauthn-admin: # Inspired by https://github.com/dmotte/misc/tree/main/examples/docker-compose/sftpgo
    image: docker.io/drakkan/sftpgo:v2.6-alpine
    restart: always
    ports: ["2022:2022"]
    volumes:
      - webauthn-admin-home:/var/lib/sftpgo
      - ./volumes/webauthn-proxy-config/users.yml:/serve/users.yml
    command: >
      sftpgo portable --log-file-path=/dev/stdout --sftpd-port=2022 --username=user --directory=/serve
      --permissions=list,download,upload,overwrite

  whoami:
    image: docker.io/traefik/whoami:v1.10
    restart: always
    hostname: whoami

  webserver:
    image: docker.io/joseluisq/static-web-server:2
    restart: always
    volumes: [./volumes/webserver-public:/public:ro]

volumes:
  webauthn-admin-home: {}
