---
accessLog: { addInternals: true }

providers:
  file: { directory: /etc/traefik/dynamic }

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      # Set this only if this Traefik instance is running behind another
      # reverse proxy
      trustedIPs: ["0.0.0.0/0"] # Always trust the X-Forwarded-* headers
